---
on:
  push:
    paths:
      - VERSION

jobs:
  set-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Update Readme
        uses: udondan/ver2doc@v1.0.1
        with:
          FILE: README.md
          PATTERN: (udondan/cdk-nodejs(:?\@v|:))[0-9.]+
          REPLACE: \${1}${VERSION}

      - name: Update Action
        uses: udondan/ver2doc@v1.0.1
        with:
          FILE: README.md
          PATTERN: (udondan/cdk-nodejs:)[0-9.]+
          REPLACE: \${1}${VERSION}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || git commit -m "Updates version references" -a

      - name: Push changes
        run: >
          [[ "${{ github.ref }}" == refs/tags/* ]] ||
          git push "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}
